/* =============================================================
   DATOS INICIALES: productos, insumos y recetas de John Wick
   Generado a partir del Excel de costeo (john wick.xlsx).
   Ejecutar después de 01_BaseDatos.sql.

   Cada ingrediente del Excel traía su COSTO por porción. Aquí se
   convirtió en cantidad: cantidad = costo en la receta / costo unitario
   del insumo. Ej.: Tocineta 4500 / 1500 = 3 porciones.
   Revise las unidades (UND, PORC) y ajústelas a su medida real.
   ============================================================= */
USE DB_INVENTARIO_COMIDAS;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
UPDATE CONFIGURACION SET NombreNegocio = 'John Wick', MensajeTicket = '¡Gracias por tu compra! Vuelve pronto.';
GO

INSERT INTO CATEGORIA (Descripcion) VALUES ('Abarrotes'), ('Carnes'), ('Congelados'), ('Desechables'), ('Lácteos'), ('Panadería'), ('Salsas'), ('Verduras');
INSERT INTO CATEGORIA_MENU (Nombre, Icono, Orden) VALUES ('Hamburguesas', N'🍔', 1), ('Perros', N'🌭', 2), ('Papas', N'🍟', 3), ('Platos', N'🍽️', 4), ('Mexicano y más', N'🌯', 5);

INSERT INTO INSUMO (Codigo, Nombre, IdCategoria, UnidadMedida, StockMinimo, CostoUnitario)
SELECT v.Codigo, v.Nombre, c.IdCategoria, v.Unidad, v.Minimo, v.Costo FROM (VALUES
  ('BOLSA', 'Bolsa', 'Desechables', 'UND', 50, 100),
  ('SERV', 'Servilleta', 'Desechables', 'UND', 150, 100),
  ('TENE', 'Tenedor', 'Desechables', 'UND', 50, 100),
  ('CUCH', 'Cuchillo', 'Desechables', 'UND', 30, 100),
  ('ALUM', 'Papel aluminio (porción)', 'Desechables', 'PORC', 50, 100),
  ('PLATO', 'Plato desechable', 'Desechables', 'UND', 30, 300),
  ('CAJA', 'Caja de empaque', 'Desechables', 'UND', 30, 1200),
  ('C1', 'Caja C1 hamburguesa', 'Desechables', 'UND', 30, 300),
  ('PORTAP', 'Porta perro', 'Desechables', 'UND', 30, 100),
  ('PORTAH', 'Porta hamburguesa', 'Desechables', 'UND', 30, 100),
  ('PANP', 'Pan de perro artesanal', 'Panadería', 'UND', 20, 1000),
  ('PANH', 'Pan de hamburguesa', 'Panadería', 'UND', 30, 1000),
  ('AREPA', 'Arepa', 'Panadería', 'UND', 20, 300),
  ('TORT', 'Tortilla', 'Panadería', 'UND', 10, 1200),
  ('PATAC', 'Patacón', 'Verduras', 'UND', 10, 1700),
  ('NACHO', 'Nachos (porción)', 'Abarrotes', 'PORC', 10, 1500),
  ('CARNEH', 'Carne de hamburguesa', 'Carnes', 'UND', 30, 3500),
  ('CARNED', 'Carne desmechada (porción)', 'Carnes', 'PORC', 15, 4000),
  ('PULLED', 'Carne pulled pork (porción)', 'Carnes', 'PORC', 15, 3500),
  ('POLLO', 'Pollo desmechado 80 g', 'Carnes', 'PORC', 15, 3000),
  ('SALCH', 'Salchicha 100 g', 'Carnes', 'UND', 20, 1200),
  ('SALCHA', 'Salchicha americana (perro)', 'Carnes', 'UND', 20, 2900),
  ('TOCI', 'Tocineta (porción)', 'Carnes', 'PORC', 30, 1500),
  ('CHICH', 'Chicharrón 100 g', 'Carnes', 'PORC', 10, 2500),
  ('CHICHC', 'Chicharrón caramelizado (porción)', 'Carnes', 'PORC', 10, 3500),
  ('CHORC', 'Chorizo coctelero', 'Carnes', 'UND', 20, 700),
  ('CHORCA', 'Chorizo casero', 'Carnes', 'UND', 10, 3100),
  ('CHORP', 'Chorizo para perro', 'Carnes', 'UND', 10, 3500),
  ('BUTIF', 'Butifarra', 'Carnes', 'UND', 20, 450),
  ('CHUZO', 'Chuzo de pollo', 'Carnes', 'UND', 10, 4200),
  ('LOMO', 'Lomo de cerdo (porción)', 'Carnes', 'PORC', 10, 5000),
  ('CHURR', 'Churrasco', 'Carnes', 'UND', 5, 12000),
  ('QMOZ', 'Queso mozzarella (porción)', 'Lácteos', 'PORC', 40, 500),
  ('QLON', 'Queso en lonchita', 'Lácteos', 'UND', 20, 500),
  ('CREMA', 'Crema de leche (porción)', 'Lácteos', 'PORC', 10, 1000),
  ('HCOD', 'Huevo de codorniz', 'Lácteos', 'UND', 30, 300),
  ('HUEVO', 'Huevo', 'Lácteos', 'UND', 15, 300),
  ('ENSAL', 'Ensalada (porción)', 'Verduras', 'PORC', 20, 500),
  ('LECH', 'Lechuga (porción)', 'Verduras', 'PORC', 20, 500),
  ('TOMATE', 'Tomate (porción)', 'Verduras', 'PORC', 20, 500),
  ('PEPINO', 'Pepino (porción)', 'Verduras', 'PORC', 10, 800),
  ('PINA', 'Piña (porción)', 'Verduras', 'PORC', 10, 1000),
  ('MADURO', 'Maduro (porción)', 'Verduras', 'PORC', 10, 500),
  ('GUAC', 'Guacamole (porción)', 'Salsas', 'PORC', 15, 500),
  ('PICO', 'Pico de gallo (porción)', 'Salsas', 'PORC', 15, 500),
  ('SALSAS', 'Salsas (porción)', 'Salsas', 'PORC', 40, 1000),
  ('MAICIT', 'Maicitos (porción)', 'Abarrotes', 'PORC', 15, 1000),
  ('MAIZ', 'Maíz desgranado (porción)', 'Abarrotes', 'PORC', 10, 3000),
  ('RIPIO', 'Papa ripio (porción)', 'Abarrotes', 'PORC', 20, 500),
  ('PAPA330', 'Papa a la francesa 330 g', 'Congelados', 'PORC', 20, 2600),
  ('PAPAAC', 'Papa acompañante (porción)', 'Congelados', 'PORC', 20, 1200)
) v (Codigo, Nombre, Categoria, Unidad, Minimo, Costo) INNER JOIN CATEGORIA c ON c.Descripcion = v.Categoria;

INSERT INTO PRODUCTO_MENU (Nombre, IdCategoriaMenu, Precio)
SELECT v.Nombre, c.IdCategoriaMenu, v.Precio FROM (VALUES
  ('Perro caliente', 'Perros', 18000),
  ('Perra callejera', 'Perros', 19000),
  ('Hamburguesa callejera', 'Hamburguesas', 21000),
  ('Hamburguesa hawaiana', 'Hamburguesas', 24000),
  ('Hamburguesa Philadelphia', 'Hamburguesas', 26000),
  ('Chuzo de pollo', 'Platos', 24000),
  ('Burrito de carne', 'Mexicano y más', 25000),
  ('Burrito de pollo', 'Mexicano y más', 23000),
  ('Papa paisa', 'Papas', 26500),
  ('Papa pollo', 'Papas', 26500),
  ('Papa mexicana', 'Papas', 28000),
  ('Papa tradicional', 'Papas', 20000),
  ('Choripapa', 'Papas', 24000),
  ('Patacón de carne', 'Mexicano y más', 23000),
  ('Patacón de pollo', 'Mexicano y más', 20000),
  ('Lomo de cerdo', 'Platos', 28000),
  ('Churrasco', 'Platos', 32000),
  ('Arepa burguer', 'Hamburguesas', 17000),
  ('Desgranado', 'Mexicano y más', 22000),
  ('Hamburguesa pulled pork', 'Hamburguesas', 20000),
  ('Hamburguesa John Wick', 'Hamburguesas', 28000),
  ('Papas full bacon', 'Papas', 23500),
  ('Papas John Wick', 'Papas', 30000),
  ('Choriperro', 'Perros', 17000)
) v (Nombre, Categoria, Precio) INNER JOIN CATEGORIA_MENU c ON c.Nombre = v.Categoria;

INSERT INTO RECETA (IdProducto, IdInsumo, Cantidad)
SELECT p.IdProducto, i.IdInsumo, v.Cantidad FROM (VALUES
  ('Perro caliente', 'PORTAP', 1),
  ('Perro caliente', 'PANP', 1),
  ('Perro caliente', 'SALCHA', 1),
  ('Perro caliente', 'ENSAL', 2),
  ('Perro caliente', 'TOCI', 1),
  ('Perro caliente', 'QMOZ', 3),
  ('Perro caliente', 'RIPIO', 1),
  ('Perro caliente', 'HCOD', 1),
  ('Perro caliente', 'SALSAS', 1),
  ('Perro caliente', 'SERV', 2),
  ('Perro caliente', 'ALUM', 5),
  ('Perro caliente', 'BOLSA', 1),
  ('Perra callejera', 'PORTAP', 1),
  ('Perra callejera', 'PANP', 1),
  ('Perra callejera', 'ENSAL', 1),
  ('Perra callejera', 'TOCI', 3),
  ('Perra callejera', 'QMOZ', 2),
  ('Perra callejera', 'RIPIO', 1),
  ('Perra callejera', 'HCOD', 1),
  ('Perra callejera', 'SALSAS', 1),
  ('Perra callejera', 'SERV', 2),
  ('Perra callejera', 'ALUM', 5),
  ('Perra callejera', 'BOLSA', 1),
  ('Hamburguesa callejera', 'C1', 1),
  ('Hamburguesa callejera', 'PORTAH', 1),
  ('Hamburguesa callejera', 'PANH', 1),
  ('Hamburguesa callejera', 'ENSAL', 1),
  ('Hamburguesa callejera', 'RIPIO', 1),
  ('Hamburguesa callejera', 'CARNEH', 1),
  ('Hamburguesa callejera', 'QMOZ', 3),
  ('Hamburguesa callejera', 'TOCI', 1),
  ('Hamburguesa callejera', 'SALSAS', 1),
  ('Hamburguesa callejera', 'SERV', 3),
  ('Hamburguesa callejera', 'BOLSA', 1),
  ('Hamburguesa hawaiana', 'C1', 1),
  ('Hamburguesa hawaiana', 'PORTAH', 1),
  ('Hamburguesa hawaiana', 'PANH', 1),
  ('Hamburguesa hawaiana', 'LECH', 1),
  ('Hamburguesa hawaiana', 'TOMATE', 1.4),
  ('Hamburguesa hawaiana', 'CARNEH', 1),
  ('Hamburguesa hawaiana', 'PINA', 1),
  ('Hamburguesa hawaiana', 'QMOZ', 3),
  ('Hamburguesa hawaiana', 'SALSAS', 1),
  ('Hamburguesa hawaiana', 'TOCI', 1),
  ('Hamburguesa hawaiana', 'SERV', 3),
  ('Hamburguesa hawaiana', 'BOLSA', 1),
  ('Hamburguesa Philadelphia', 'PORTAH', 3),
  ('Hamburguesa Philadelphia', 'C1', 1),
  ('Hamburguesa Philadelphia', 'PANH', 1),
  ('Hamburguesa Philadelphia', 'LECH', 1),
  ('Hamburguesa Philadelphia', 'TOMATE', 1.4),
  ('Hamburguesa Philadelphia', 'CARNEH', 1),
  ('Hamburguesa Philadelphia', 'PEPINO', 1),
  ('Hamburguesa Philadelphia', 'QMOZ', 4),
  ('Hamburguesa Philadelphia', 'SALSAS', 1),
  ('Hamburguesa Philadelphia', 'TOCI', 1),
  ('Hamburguesa Philadelphia', 'SERV', 3),
  ('Hamburguesa Philadelphia', 'BOLSA', 1),
  ('Chuzo de pollo', 'CAJA', 1),
  ('Chuzo de pollo', 'CHUZO', 1),
  ('Chuzo de pollo', 'PAPAAC', 1),
  ('Chuzo de pollo', 'ENSAL', 2.4),
  ('Chuzo de pollo', 'AREPA', 1),
  ('Chuzo de pollo', 'QLON', 1),
  ('Chuzo de pollo', 'SALSAS', 1),
  ('Chuzo de pollo', 'BOLSA', 1),
  ('Chuzo de pollo', 'TENE', 1),
  ('Burrito de carne', 'TORT', 1),
  ('Burrito de carne', 'QLON', 1),
  ('Burrito de carne', 'LECH', 1),
  ('Burrito de carne', 'MAICIT', 1),
  ('Burrito de carne', 'TOCI', 1),
  ('Burrito de carne', 'CARNED', 1.5),
  ('Burrito de carne', 'NACHO', 1),
  ('Burrito de carne', 'GUAC', 1),
  ('Burrito de carne', 'PICO', 1),
  ('Burrito de carne', 'CAJA', 1),
  ('Burrito de carne', 'SERV', 3),
  ('Burrito de carne', 'BOLSA', 1),
  ('Burrito de carne', 'TENE', 1),
  ('Burrito de carne', 'CUCH', 1),
  ('Burrito de pollo', 'TORT', 1),
  ('Burrito de pollo', 'QLON', 1),
  ('Burrito de pollo', 'LECH', 1),
  ('Burrito de pollo', 'MAICIT', 1),
  ('Burrito de pollo', 'TOCI', 1),
  ('Burrito de pollo', 'NACHO', 1),
  ('Burrito de pollo', 'GUAC', 1),
  ('Burrito de pollo', 'PICO', 1),
  ('Burrito de pollo', 'CAJA', 1),
  ('Burrito de pollo', 'SERV', 3),
  ('Burrito de pollo', 'BOLSA', 1),
  ('Burrito de pollo', 'TENE', 1),
  ('Burrito de pollo', 'CUCH', 1),
  ('Burrito de pollo', 'POLLO', 2),
  ('Papa paisa', 'CAJA', 1),
  ('Papa paisa', 'PAPA330', 1),
  ('Papa paisa', 'CHICH', 1),
  ('Papa paisa', 'TOCI', 1),
  ('Papa paisa', 'CHORC', 2),
  ('Papa paisa', 'BUTIF', 3),
  ('Papa paisa', 'MADURO', 1),
  ('Papa paisa', 'SALSAS', 1),
  ('Papa paisa', 'SERV', 3),
  ('Papa paisa', 'TENE', 1),
  ('Papa paisa', 'BOLSA', 1),
  ('Papa pollo', 'CAJA', 1),
  ('Papa pollo', 'PAPA330', 1),
  ('Papa pollo', 'POLLO', 1),
  ('Papa pollo', 'MAICIT', 1),
  ('Papa pollo', 'TOCI', 1),
  ('Papa pollo', 'QMOZ', 2),
  ('Papa pollo', 'HCOD', 2),
  ('Papa pollo', 'SALSAS', 1),
  ('Papa pollo', 'SERV', 3),
  ('Papa pollo', 'TENE', 1),
  ('Papa pollo', 'BOLSA', 1),
  ('Papa mexicana', 'CAJA', 1),
  ('Papa mexicana', 'PAPA330', 1),
  ('Papa mexicana', 'CARNED', 1),
  ('Papa mexicana', 'MAICIT', 1),
  ('Papa mexicana', 'GUAC', 2),
  ('Papa mexicana', 'PICO', 2),
  ('Papa mexicana', 'QMOZ', 2),
  ('Papa mexicana', 'TENE', 1),
  ('Papa mexicana', 'SERV', 3),
  ('Papa mexicana', 'SALSAS', 1),
  ('Papa mexicana', 'BOLSA', 1),
  ('Papa tradicional', 'CAJA', 1),
  ('Papa tradicional', 'PAPA330', 1),
  ('Papa tradicional', 'SALCH', 1),
  ('Papa tradicional', 'HCOD', 2),
  ('Papa tradicional', 'QMOZ', 2),
  ('Papa tradicional', 'SALSAS', 1),
  ('Papa tradicional', 'TOCI', 1),
  ('Papa tradicional', 'SERV', 3),
  ('Papa tradicional', 'BOLSA', 1),
  ('Papa tradicional', 'TENE', 1),
  ('Choripapa', 'CAJA', 1),
  ('Choripapa', 'PAPA330', 1),
  ('Choripapa', 'CHORCA', 1),
  ('Choripapa', 'CHORC', 2),
  ('Choripapa', 'MADURO', 1),
  ('Choripapa', 'SALSAS', 1),
  ('Choripapa', 'TOCI', 1),
  ('Choripapa', 'SERV', 3),
  ('Choripapa', 'BOLSA', 1),
  ('Choripapa', 'TENE', 1),
  ('Patacón de carne', 'CARNED', 1),
  ('Patacón de carne', 'PATAC', 1),
  ('Patacón de carne', 'GUAC', 2),
  ('Patacón de carne', 'RIPIO', 1),
  ('Patacón de carne', 'QMOZ', 3),
  ('Patacón de carne', 'SALSAS', 1),
  ('Patacón de carne', 'SERV', 3),
  ('Patacón de carne', 'ALUM', 5),
  ('Patacón de carne', 'PLATO', 1),
  ('Patacón de carne', 'BOLSA', 1),
  ('Patacón de pollo', 'PATAC', 1),
  ('Patacón de pollo', 'GUAC', 2),
  ('Patacón de pollo', 'RIPIO', 1),
  ('Patacón de pollo', 'QMOZ', 3),
  ('Patacón de pollo', 'SALSAS', 1),
  ('Patacón de pollo', 'SERV', 3),
  ('Patacón de pollo', 'ALUM', 5),
  ('Patacón de pollo', 'PLATO', 1),
  ('Patacón de pollo', 'BOLSA', 1),
  ('Patacón de pollo', 'POLLO', 1.333),
  ('Lomo de cerdo', 'CAJA', 1),
  ('Lomo de cerdo', 'PAPAAC', 1),
  ('Lomo de cerdo', 'AREPA', 1),
  ('Lomo de cerdo', 'QLON', 1),
  ('Lomo de cerdo', 'ENSAL', 2.4),
  ('Lomo de cerdo', 'LOMO', 1),
  ('Lomo de cerdo', 'SERV', 3),
  ('Lomo de cerdo', 'TENE', 1),
  ('Lomo de cerdo', 'CUCH', 1),
  ('Lomo de cerdo', 'BOLSA', 1),
  ('Churrasco', 'CAJA', 1),
  ('Churrasco', 'PAPAAC', 1),
  ('Churrasco', 'AREPA', 1),
  ('Churrasco', 'QLON', 1),
  ('Churrasco', 'ENSAL', 2.4),
  ('Churrasco', 'CHURR', 1),
  ('Churrasco', 'SERV', 3),
  ('Churrasco', 'TENE', 1),
  ('Churrasco', 'CUCH', 1),
  ('Churrasco', 'BOLSA', 1),
  ('Arepa burguer', 'AREPA', 1.667),
  ('Arepa burguer', 'CARNEH', 1),
  ('Arepa burguer', 'ENSAL', 2),
  ('Arepa burguer', 'QMOZ', 3),
  ('Arepa burguer', 'RIPIO', 1),
  ('Arepa burguer', 'HUEVO', 1),
  ('Arepa burguer', 'SALSAS', 1),
  ('Arepa burguer', 'PLATO', 1),
  ('Arepa burguer', 'SERV', 3),
  ('Arepa burguer', 'BOLSA', 1),
  ('Desgranado', 'MAIZ', 1),
  ('Desgranado', 'CREMA', 1),
  ('Desgranado', 'TOCI', 1),
  ('Desgranado', 'POLLO', 1),
  ('Desgranado', 'QMOZ', 3),
  ('Desgranado', 'RIPIO', 1),
  ('Desgranado', 'SALSAS', 1),
  ('Desgranado', 'C1', 1),
  ('Desgranado', 'SERV', 3),
  ('Desgranado', 'TENE', 1),
  ('Desgranado', 'BOLSA', 1),
  ('Hamburguesa pulled pork', 'PANH', 1),
  ('Hamburguesa pulled pork', 'PULLED', 1),
  ('Hamburguesa pulled pork', 'TOMATE', 1),
  ('Hamburguesa pulled pork', 'TOCI', 1),
  ('Hamburguesa pulled pork', 'QMOZ', 3),
  ('Hamburguesa pulled pork', 'LECH', 1),
  ('Hamburguesa pulled pork', 'SALSAS', 1),
  ('Hamburguesa pulled pork', 'C1', 1.333),
  ('Hamburguesa pulled pork', 'SERV', 3),
  ('Hamburguesa pulled pork', 'PORTAH', 2),
  ('Hamburguesa pulled pork', 'BOLSA', 1),
  ('Hamburguesa John Wick', 'PANH', 1),
  ('Hamburguesa John Wick', 'CARNEH', 1),
  ('Hamburguesa John Wick', 'CHICHC', 1),
  ('Hamburguesa John Wick', 'TOCI', 1),
  ('Hamburguesa John Wick', 'QMOZ', 3),
  ('Hamburguesa John Wick', 'TOMATE', 1),
  ('Hamburguesa John Wick', 'LECH', 1),
  ('Hamburguesa John Wick', 'PEPINO', 1),
  ('Hamburguesa John Wick', 'SALSAS', 1),
  ('Hamburguesa John Wick', 'SERV', 3),
  ('Hamburguesa John Wick', 'C1', 1),
  ('Hamburguesa John Wick', 'PORTAH', 2),
  ('Hamburguesa John Wick', 'BOLSA', 1),
  ('Papas full bacon', 'CAJA', 1),
  ('Papas full bacon', 'PAPA330', 1),
  ('Papas full bacon', 'TOCI', 4),
  ('Papas full bacon', 'HCOD', 4),
  ('Papas full bacon', 'SERV', 3),
  ('Papas full bacon', 'TENE', 1),
  ('Papas full bacon', 'SALSAS', 1),
  ('Papas full bacon', 'BOLSA', 1),
  ('Papas John Wick', 'CAJA', 1),
  ('Papas John Wick', 'PAPA330', 1),
  ('Papas John Wick', 'PULLED', 1),
  ('Papas John Wick', 'CHICHC', 1),
  ('Papas John Wick', 'SALCH', 1),
  ('Papas John Wick', 'QMOZ', 3),
  ('Papas John Wick', 'SERV', 3),
  ('Papas John Wick', 'TENE', 1),
  ('Papas John Wick', 'SALSAS', 1),
  ('Papas John Wick', 'BOLSA', 1),
  ('Choriperro', 'PANP', 1),
  ('Choriperro', 'QMOZ', 3),
  ('Choriperro', 'CHORP', 1),
  ('Choriperro', 'PICO', 1),
  ('Choriperro', 'RIPIO', 1),
  ('Choriperro', 'SALSAS', 1),
  ('Choriperro', 'SERV', 3),
  ('Choriperro', 'ALUM', 3),
  ('Choriperro', 'BOLSA', 1)
) v (Producto, Codigo, Cantidad)
INNER JOIN PRODUCTO_MENU p ON p.Nombre = v.Producto
INNER JOIN INSUMO i ON i.Codigo = v.Codigo;
GO

/* Adiciones y modificadores */
INSERT INTO MODIFICADOR (Nombre, Precio, IdInsumo, Cantidad)
SELECT v.Nombre, v.Precio, i.IdInsumo, v.Cantidad FROM (VALUES
  ('Doble carne',          7000, 'CARNEH',  1),
  ('Doble carne pulled pork', 7000, 'PULLED', 1),
  ('Adición de tocineta',  2500, 'TOCI',    1),
  ('Adición de queso',     2500, 'QMOZ',    3),
  ('Adición de huevos de codorniz', 1500, 'HCOD', 3),
  ('Adición de papa',      3000, 'PAPAAC',  1),
  ('Sin ensalada',            0, 'ENSAL',  -2),
  ('Sin salsas',              0, 'SALSAS', -1)
) v (Nombre, Precio, Codigo, Cantidad) INNER JOIN INSUMO i ON i.Codigo = v.Codigo;

INSERT INTO PRODUCTO_MODIFICADOR (IdProducto, IdModificador)
SELECT p.IdProducto, m.IdModificador
FROM PRODUCTO_MENU p INNER JOIN CATEGORIA_MENU c ON c.IdCategoriaMenu = p.IdCategoriaMenu
CROSS JOIN MODIFICADOR m
WHERE (m.Nombre IN ('Adición de tocineta', 'Adición de queso', 'Sin salsas'))
   OR (m.Nombre = 'Doble carne' AND c.Nombre = 'Hamburguesas' AND p.Nombre NOT LIKE '%pulled pork%')
   OR (m.Nombre = 'Doble carne pulled pork' AND p.Nombre LIKE '%pulled pork%')
   OR (m.Nombre = 'Adición de huevos de codorniz' AND c.Nombre IN ('Perros', 'Papas'))
   OR (m.Nombre = 'Adición de papa' AND c.Nombre IN ('Hamburguesas', 'Perros'))
   OR (m.Nombre = 'Sin ensalada' AND EXISTS (SELECT 1 FROM RECETA r INNER JOIN INSUMO i ON i.IdInsumo = r.IdInsumo
                                             WHERE r.IdProducto = p.IdProducto AND i.Codigo = 'ENSAL'));

INSERT INTO PROVEEDOR (Documento, RazonSocial, Telefono) VALUES
('000000001', 'Proveedor general', '');
GO

/* Inventario inicial de ejemplo: 3 veces el stock mínimo de cada insumo.
   Reemplácelo haciendo un "Conteo físico" con las cantidades reales. */
DECLARE @Id INT, @Cant DECIMAL(12,3), @Costo DECIMAL(12,2);
DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT IdInsumo, StockMinimo * 3, CostoUnitario FROM INSUMO;
OPEN c; FETCH NEXT FROM c INTO @Id, @Cant, @Costo;
BEGIN TRANSACTION;
WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC SP_STOCK_APLICAR 1, @Id, 'ENTRADA', @Cant, @Costo, 1, NULL, 'Inventario inicial', 1, NULL;
    FETCH NEXT FROM c INTO @Id, @Cant, @Costo;
END
COMMIT;
CLOSE c; DEALLOCATE c;

/* Caja abierta para poder vender desde el primer ingreso */
INSERT INTO CAJA (IdSede, IdUsuarioApertura, BaseInicial) VALUES (1, 1, 100000);
GO

/* Descripciones que se muestran en las tarjetas del punto de venta */
UPDATE p SET Descripcion = d.Descripcion
FROM PRODUCTO_MENU p INNER JOIN (VALUES
    ('Arepa burguer', 'Arepa con carne de hamburguesa, huevo, queso mozzarella, ensalada y papa ripio'),
    ('Hamburguesa callejera', 'Carne de res, tocineta, queso mozzarella, ensalada y papa ripio'),
    ('Hamburguesa hawaiana', 'Carne de res, tocineta, queso mozzarella, piña, lechuga y tomate'),
    ('Hamburguesa John Wick', 'Carne de res, tocineta, chicharrón caramelizado, queso mozzarella y vegetales'),
    ('Hamburguesa Philadelphia', 'Carne de res, tocineta, queso mozzarella, lechuga, tomate y pepino'),
    ('Hamburguesa pulled pork', 'Cerdo desmechado, tocineta, queso mozzarella, lechuga y tomate'),
    ('Choriperro', 'Chorizo en pan artesanal, queso mozzarella, pico de gallo y papa ripio'),
    ('Perra callejera', 'Tocineta, queso mozzarella, huevos de codorniz, ensalada y papa ripio'),
    ('Perro caliente', 'Salchicha americana, tocineta, queso mozzarella, huevos de codorniz y papa ripio'),
    ('Choripapa', 'Papa a la francesa con chorizo casero, chorizo coctelero, tocineta y maduro'),
    ('Papa mexicana', 'Papa a la francesa con carne desmechada, maicitos, guacamole y pico de gallo'),
    ('Papa paisa', 'Papa a la francesa con chicharrón, chorizo, butifarra, tocineta y maduro'),
    ('Papa pollo', 'Papa a la francesa con pollo desmechado, maicitos, tocineta y queso mozzarella'),
    ('Papa tradicional', 'Papa a la francesa con salchicha, tocineta, queso mozzarella y huevos de codorniz'),
    ('Papas full bacon', 'Papa a la francesa con tocineta y huevos de codorniz'),
    ('Papas John Wick', 'Papa a la francesa con pulled pork, salchicha, chicharrón caramelizado y queso'),
    ('Churrasco', 'Churrasco a la parrilla con papa, arepa con queso y ensalada'),
    ('Chuzo de pollo', 'Chuzo de pollo con papa, arepa con queso y ensalada'),
    ('Lomo de cerdo', 'Lomo de cerdo con papa, arepa con queso y ensalada'),
    ('Burrito de carne', 'Tortilla con carne desmechada, tocineta, nachos, guacamole y pico de gallo'),
    ('Burrito de pollo', 'Tortilla con pollo desmechado, tocineta, nachos, guacamole y pico de gallo'),
    ('Desgranado', 'Maíz desgranado con pollo, tocineta, queso mozzarella, crema y papa ripio'),
    ('Patacón de carne', 'Patacón con carne desmechada, queso mozzarella, guacamole y papa ripio'),
    ('Patacón de pollo', 'Patacón con pollo desmechado, queso mozzarella, guacamole y papa ripio')
) d (Nombre, Descripcion) ON d.Nombre = p.Nombre;
GO
